### ISSUE TITLE
Maintenance of this repo

### ISSUE THREAD

**Issue by sylvain-hamel** [distros/bootstrap-less#2]
Hi,
- Are updates to this repo automated?
- The version 3.3.8 does not match the latest twbs release (3.3.5). Should it?

Thanks

**Comment by Aaike** [comment]
Hi , no it is not automated (i might look into that though)
I just update it whenever somebody or myself needs it to be updated.

So with that i have just updated the repo to be inline with the bootstrap 3.3.5 release

The version for this repo is not the same as that of bootstrap because sometimes we change some things that are not related to a bootstrap update  but we still need to tag a new version for it

I have added the bootstrap version that is included with this package in the readme.md so there is no confusion

if you need it to be updated later on just ping me or submit a PR, thanks !
